# Generated by Django 6.0.2 on 2026-03-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmm', '0002_geeksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='mapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
