# Generated by Django 6.0.2 on 2026-03-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmm', '0003_mapdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapdata',
            name='x',
        ),
        migrations.RemoveField(
            model_name='mapdata',
            name='y',
        ),
    ]
