# Generated by Django 6.0.2 on 2026-03-03 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmm', '0004_remove_mapdata_x_remove_mapdata_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='mapObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mapdata',
            name='active',
        ),
        migrations.AddField(
            model_name='mapdata',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mapdata',
            name='y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mapdata',
            name='mapObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hmm.mapobjects'),
        ),
    ]
